name: Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  # Customize this to match the name of the solution/project Premake generates
  PROJECT_NAME: "Mixture"
  BUILD_CONFIG: "Release"
  CI: "true"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Ubuntu 24.04
            setup_script: bash ./Scripts/Setup-Unix.sh
            build_command: make config=release

          - os: windows-latest
            name: Windows
            setup_script: pwsh ./Scripts/Setup-Windows.ps1
            build_command: msbuild /p:Configuration=Release /p:Platform=x64

          - os: macos-latest
            name: MacOS
            setup_script: bash ./Scripts/Setup-Unix.sh
            build_command: xcodebuild -workspace Mixture.xcworkspace -scheme Tests -configuration Release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Universal SDK Installer
    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        vulkan_version: 1.3.296.0
        cache: true
        optional_components: com.lunarg.vulkan.vma

    - name: Run Setup Script
      run: ${{ matrix.setup_script }}

    - name: Build
      run: ${{ matrix.build_command }}


